name: Build and Test
permissions:
  contents: read

on:
  push:
    branches: [gh-pages]
  pull_request:
    branches: [gh-pages]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        submodules: true

    - name: Set up Ruby
      uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
      with:
        ruby-version: 3.3.4
        bundler-cache: true

    - name: Run tests
      run: ./script/cibuild
